image: python:latest
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths:
    - .cache/pip
    - venv/
before_script:
  - python -V
  - pip install pylint
  - pip install -r requirements.txt
lint:
  script:
    - pylint --disable=R,C,W existentcontraption.py
testcli:
  script:
    - mkdir clioutput
    - chmod -x eccli.py
    - python eccli.py --path="testxml/punchypunch" --outputfolder=".temp" --materialthickness=5 --scale=1 --machine=laser
  artifacts:
    paths:
      - clioutput/*.svg
    expire_in: never
